// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Soporte API",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tuya/device/{deviceId}": {
            "get": {
                "description": "Obtiene información de un dispositivo específico por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tuya"
                ],
                "summary": "Obtener información de dispositivo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del dispositivo",
                        "name": "deviceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Información del dispositivo obtenida exitosamente",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.TuyaAPIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.TuyaDeviceResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "ID de dispositivo requerido",
                        "schema": {
                            "$ref": "#/definitions/handlers.TuyaAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Error al obtener información del dispositivo",
                        "schema": {
                            "$ref": "#/definitions/handlers.TuyaAPIResponse"
                        }
                    }
                }
            }
        },
        "/tuya/token": {
            "get": {
                "description": "Obtiene un token de acceso de Tuya Cloud API usando las credenciales configuradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tuya"
                ],
                "summary": "Obtener token de acceso de Tuya",
                "responses": {
                    "200": {
                        "description": "Token obtenido exitosamente",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.TuyaAPIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.TuyaTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Error al obtener token",
                        "schema": {
                            "$ref": "#/definitions/handlers.TuyaAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.TuyaAPIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "debug": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.TuyaDeviceResponse": {
            "type": "object",
            "properties": {
                "result": {},
                "success": {
                    "type": "boolean"
                },
                "t": {
                    "type": "integer"
                },
                "tid": {
                    "type": "string"
                }
            }
        },
        "handlers.TuyaTokenResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "object",
                    "properties": {
                        "access_token": {
                            "type": "string"
                        },
                        "expire_time": {
                            "type": "integer"
                        },
                        "refresh_token": {
                            "type": "string"
                        },
                        "uid": {
                            "type": "string"
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                },
                "t": {
                    "type": "integer"
                },
                "tid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API Gateway Tuya Go - SDK Oficial",
	Description:      "API Gateway para Tuya Cloud siguiendo el patrón del SDK oficial",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
